security:
    password_hashers:
        App\Entity\User: 'auto'  # Utilise bcrypt ou argon2 par défaut

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email  # ou 'pseudo' si tu préfères

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_database  # Fournisseur basé sur Doctrine
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_home
            custom_authenticator: App\Security\LoginAuthenticator

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Le plus bas pour bcrypt
                time_cost: 3  # Le plus bas pour argon
                memory_cost: 10  # Le plus bas pour argon
